name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: "20"

      # Generate the deployment package
      - name: Generate deployment package
        run: |
          # Remove unnecessary files
          rm -rf ./node_modules

          # Create the .zip file
          zip -r deploy.zip . -x '*.git*'

      # Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Check if the S3 bucket exists, and create it if it doesn't
      - name: Create S3 bucket if it doesn't exist
        run: |
          if ! aws s3api head-bucket --bucket ceartas-elb-app-development 2>/dev/null; then
            aws s3api create-bucket --bucket ceartas-elb-app-development
            echo "Bucket created successfully."
          else
            echo "Bucket already exists."
          fi

      # Check if the Elastic Beanstalk application exists, and create it if it doesn't
      - name: Create Elastic Beanstalk application if it doesn't exist
        run: |
          # Describe the application
          APP_EXISTS=$(aws elasticbeanstalk describe-applications --application-names ceartas --query 'Applications' --output text)

          # Check if the Applications array is empty
          if [ -z "$APP_EXISTS" ]; then
            aws elasticbeanstalk create-application --application-name ceartas
            echo "Elastic Beanstalk application created successfully."
          else
            echo "Elastic Beanstalk application already exists."
          fi

      # Check if the Elastic Beanstalk environment exists, and create it if it doesn't
      - name: Create Elastic Beanstalk environment if it doesn't exist
        run: |
          # Describe the environment
          ENV_EXISTS=$(aws elasticbeanstalk describe-environments --application-name ceartas --environment-names bare-developin --query 'Environments' --output text)

          # Check if the Environments array is empty
          if [ -z "$ENV_EXISTS" ]; then
            aws elasticbeanstalk create-environment \
              --application-name ceartas \
              --environment-name bare-developin \
              --solution-stack-name "64bit Amazon Linux 2023 v6.4.2 running Node.js 20" \
              --option-settings file://eb-config.json
            echo "Elastic Beanstalk environment created successfully."
          else
            echo "Elastic Beanstalk environment already exists."
          fi

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          existing_bucket_name: ceartas-elb-app-development
          application_name: ceartas
          environment_name: bare-developin
          wait_for_environment_recovery: 60
          use_existing_version_if_available: true
          version_label: prod-${{ github.SHA }}
          region: us-east-1
          deployment_package: deploy.zip
          version_description: ${{ github.SHA }}